const sentences = [
    "Ich esse gerne Pizza.",
    "Mein Bruder spielt Fußball.",
    "Die Katze schläft auf dem Sofa.",
    "Wir gehen jeden Tag spazieren.",
    "Sie hat ein rotes Auto.",
    "Das Wetter ist heute schön.",
    "Ich lerne Deutsch in der Schule.",
    "Meine Mutter kocht sehr gut.",
    "Er liest ein Buch im Park.",
    "Kannst du mir helfen?",
    "Der Zug fährt um 10 Uhr ab.",
    "Ich trinke Kaffee ohne Zucker.",
    "Sie singt sehr schön.",
    "Das Museum ist am Montag geschlossen.",
    "Mein Vater arbeitet als Lehrer.",
    "Wir haben zwei Hunde.",
    "Das Auto ist alt, aber zuverlässig.",
    "Ich habe meinen Schlüssel verloren.",
    "Die Kinder spielen im Garten.",
    "Er spricht drei Sprachen.",
    "Ich möchte Arzt werden.",
    "Sie geht jeden Morgen joggen.",
    "Wir essen um 18 Uhr zu Abend.",
    "Das Buch ist sehr interessant.",
    "Meine Schwester studiert Biologie.",
    "Der Apfel ist grün.",
    "Er hat blaue Augen.",
    "Wir fahren nächsten Monat in den Urlaub.",
    "Ich habe gestern einen Film gesehen.",
    "Das Restaurant ist nicht weit von hier.",
    "Können Sie das Fenster öffnen?",
    "Ich habe meine Hausaufgaben gemacht.",
    "Das Konzert war fantastisch.",
    "Sie hat lange blonde Haare.",
    "Meine Oma backt den besten Kuchen.",
    "Ich habe einen Brief an meinen Freund geschrieben.",
    "Wir müssen früh aufstehen.",
    "Er kauft ein neues Handy.",
    "Die Blumen sind sehr schön.",
    "Sie lernt für die Prüfung.",
    "Mein Geburtstag ist im Dezember.",
    "Das Zimmer ist sehr hell.",
    "Wir spielen jeden Samstag Fußball.",
    "Ich habe Kopfschmerzen.",
    "Das Essen schmeckt lecker.",
    "Sie hat einen neuen Job.",
    "Der Hund bellt laut.",
    "Meine Eltern sind sehr nett.",
    "Er trägt eine Brille.",
    "Wir gehen ins Kino.",
    "Das Kleid ist zu klein.",
    "Ich trinke gerne Tee.",
    "Sie schreibt ein Tagebuch.",
    "Das Bild hängt an der Wand.",
    "Mein Onkel hat einen Bauernhof.",
    "Wir reisen gerne.",
    "Er hat einen Fisch gefangen.",
    "Die Party beginnt um 20 Uhr.",
    "Ich habe meine Uhr verloren.",
    "Sie liest gerne Romane.",
    "Das Auto ist kaputt.",
    "Mein Zimmer ist sauber.",
    "Wir haben einen großen Garten.",
    "Er spielt Gitarre.",
    "Sie macht Yoga.",
    "Das Essen ist kalt.",
    "Ich habe einen Traum.",
    "Sie hat einen Vogel.",
    "Wir gehen zum Strand.",
    "Er hat sein Handy vergessen.",
    "Das Wasser ist tief.",
    "Meine Hose ist zu lang.",
    "Wir haben viel Spaß.",
    "Er ist mein bester Freund.",
    "Sie arbeitet in einem Büro.",
    "Die Tür ist offen.",
    "Mein Haus ist alt.",
    "Wir sehen uns am Wochenende.",
    "Er hat eine neue Uhr.",
    "Sie ist Lehrerin.",
    "Das Brot ist frisch.",
    "Ich habe einen Computer.",
    "Sie hat eine Katze.",
    "Wir fahren mit dem Fahrrad.",
    "Er sieht den Vogel.",
    "Die Lampe ist kaputt.",
    "Mein Telefon ist neu.",
    "Wir gehen ins Theater.",
    "Er hat Durst.",
    "Sie ist immer pünktlich.",
    "Das Fenster ist schmutzig.",
    "Meine Großeltern leben auf dem Land.",
    "Wir sehen einen Film.",
    "Er spielt Schach.",
    "Sie geht einkaufen.",
    "Die Suppe ist heiß.",
    "Ich habe ein neues Hemd.",
    "Sie hat ein schönes Lächeln.",
    "Wir besuchen unsere Freunde.",
    "Er hört Musik.",
    "Sie trägt einen Hut.",
    "Das Zimmer ist kalt.",
    "Meine Uhr ist schnell.",
    "Wir haben Hunger.",
    "Er ist müde."
];
